// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Folder struct {
	FolderID  pgtype.UUID        `json:"folder_id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FolderShare struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Access   string      `json:"access"`
}

type Note struct {
	NoteID    pgtype.UUID        `json:"note_id"`
	Title     string             `json:"title"`
	Body      pgtype.Text        `json:"body"`
	FolderID  pgtype.UUID        `json:"folder_id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NoteShare struct {
	NoteID pgtype.UUID `json:"note_id"`
	UserID pgtype.UUID `json:"user_id"`
	Access string      `json:"access"`
}

type Team struct {
	TeamID    int32              `json:"team_id"`
	TeamName  string             `json:"team_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamManager struct {
	TeamID int32       `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type TeamMember struct {
	TeamID int32       `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type User struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
