CREATE TABLE "users" ("user_id" uuid DEFAULT gen_random_uuid(),"username" text NOT NULL,"email" text NOT NULL,"password_hash" text NOT NULL,"role" text NOT NULL,"created_at" timestamptz DEFAULT now(),PRIMARY KEY ("user_id"),CONSTRAINT "chk_users_role" CHECK (role IN ('manager','member')));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");
CREATE TABLE "teams" ("team_id" uuid DEFAULT gen_random_uuid(),"team_name" text NOT NULL,"created_at" timestamptz DEFAULT now(),PRIMARY KEY ("team_id"));
CREATE TABLE "team_members" ("team_id" uuid DEFAULT gen_random_uuid(),"user_id" uuid,PRIMARY KEY ("team_id","user_id"));
CREATE TABLE "team_managers" ("team_id" uuid DEFAULT gen_random_uuid(),"user_id" uuid,PRIMARY KEY ("team_id","user_id"));
CREATE TABLE "folders" ("folder_id" uuid DEFAULT gen_random_uuid(),"name" text NOT NULL,"owner_id" uuid,"created_at" timestamptz DEFAULT now(),PRIMARY KEY ("folder_id"));
CREATE TABLE "notes" ("note_id" uuid DEFAULT gen_random_uuid(),"title" text NOT NULL,"body" text,"folder_id" uuid,"owner_id" uuid,"created_at" timestamptz DEFAULT now(),PRIMARY KEY ("note_id"));
CREATE TABLE "folder_shares" ("folder_id" uuid,"user_id" uuid,"access" text NOT NULL,PRIMARY KEY ("folder_id","user_id"),CONSTRAINT "chk_folder_shares_access" CHECK (access IN ('read','write')));
CREATE TABLE "note_shares" ("note_id" uuid,"user_id" uuid,"access" text NOT NULL,PRIMARY KEY ("note_id","user_id"),CONSTRAINT "chk_note_shares_access" CHECK (access IN ('read','write')));
ALTER TABLE "team_members" ADD CONSTRAINT "fk_teams_members" FOREIGN KEY ("team_id") REFERENCES "teams"("team_id");
ALTER TABLE "team_members" ADD CONSTRAINT "fk_users_team_memberships" FOREIGN KEY ("user_id") REFERENCES "users"("user_id");
ALTER TABLE "team_managers" ADD CONSTRAINT "fk_teams_managers" FOREIGN KEY ("team_id") REFERENCES "teams"("team_id");
ALTER TABLE "team_managers" ADD CONSTRAINT "fk_users_team_manager" FOREIGN KEY ("user_id") REFERENCES "users"("user_id");
ALTER TABLE "folders" ADD CONSTRAINT "fk_users_folders" FOREIGN KEY ("owner_id") REFERENCES "users"("user_id");
ALTER TABLE "notes" ADD CONSTRAINT "fk_folders_notes" FOREIGN KEY ("folder_id") REFERENCES "folders"("folder_id");
ALTER TABLE "notes" ADD CONSTRAINT "fk_users_notes" FOREIGN KEY ("owner_id") REFERENCES "users"("user_id");
ALTER TABLE "folder_shares" ADD CONSTRAINT "fk_folders_folder_shares" FOREIGN KEY ("folder_id") REFERENCES "folders"("folder_id");
ALTER TABLE "folder_shares" ADD CONSTRAINT "fk_users_folder_shares" FOREIGN KEY ("user_id") REFERENCES "users"("user_id");
ALTER TABLE "note_shares" ADD CONSTRAINT "fk_notes_note_shares" FOREIGN KEY ("note_id") REFERENCES "notes"("note_id");
ALTER TABLE "note_shares" ADD CONSTRAINT "fk_users_note_shares" FOREIGN KEY ("user_id") REFERENCES "users"("user_id");